PL-89
Pollolandia-IS/electronic-payroll-fe pull request #27
Opened 2022-06-14 05:28 UTC by AndreyEliVar

Pl-89 Pull Request

2022-06-15 06:57 UTC, julian-solisaguilar commented on styles/AddHoursEmployee.module.css
> +}
Add EOF

2022-06-15 06:58 UTC, julian-solisaguilar commented on pages/api/addHoursEmployee.js
> +
Fix document formatting, happens in other files as well

2022-06-15 20:06 UTC, AndreyEliVar commented on pages/api/addHoursEmployee.js
> +
fixed up

2022-06-15 20:06 UTC, AndreyEliVar commented on styles/AddHoursEmployee.module.css
> +}
fixed up

2022-06-18 04:25 UTC, julian-solisaguilar commented
Denegado 😡

2022-06-18 04:25 UTC, daar2510 requested changes
Please make sure you don't have outdated and unused files

2022-06-19 23:05 UTC, closed without merging