Feature/modify hours reports
Pollolandia-IS/electronic-payroll-fe pull request #50
Opened 2022-07-17 04:35 UTC by AndreyEliVar

https://ingesoftg001.atlassian.net/browse/PL-25
Complete annotations in the add hours form

2022-07-17 12:08 UTC, daar2510 commented on pages/hours.js
>      const [date, setDateState] = useState("2022-10-08 00:00:00");
Date initial value should be new Date() so it defaults to today's date

2022-07-17 12:13 UTC, daar2510 commented on pages/hours.js
> +    });
Please rename to "Todos los proyectos" like in the other pages.

2022-07-17 12:14 UTC, daar2510 commented on pages/hours.js
>      const [date, setDateState] = useState("2022-10-08 00:00:00");
Date initial value should be new Date() so it defaults to today's date

2022-07-17 12:15 UTC, daar2510 commented on pages/hours.js
> +    );
Default value should be "Todos los proyectos" instead of the first project.

2022-07-17 12:17 UTC, daar2510 commented on pages/hours.js
> +                    .concat(date.substring(11, 19)),
Dont include seconds in the hour, e.g. 2:30 instead of 2:30:00

2022-07-17 12:22 UTC, daar2510 requested changes
Fix hour format
Fix dropdown options
Fix default date when modal is opened
Period validations are missing: registering hours of future days is not allowed and neither is registering hours in dates earlier than project's start date
Also I noticed you have unused variables in many files. Some regarding the now deleted searchbar and some unused useStates.

2022-07-21 06:58 UTC, julian-solisaguilar commented on components/EmptyProjects.js
> +export default EmptyProjects;
Add EOF

2022-07-21 08:48 UTC, daar2510 approved these changes
🚀🚀

2022-07-21 08:48 UTC, merged